version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 127.0.0.1:26339:5432
    environment:
      POSTGRES_USER: director
      POSTGRES_PASSWORD: director
  ldap:
    image: osixia/openldap:1.3.0
    ports:
      - 127.0.0.1:26340:389
    environment:
      LDAP_ORGANISATION: TestOrg
      LDAP_DOMAIN: test.org
      LDAP_BASE_DN: dc=test,dc=org
      LDAP_ADMIN_PASSWORD: director
