// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event_Scope int32

const (
	Event_Terminal Event_Scope = 0
)

var Event_Scope_name = map[int32]string{
	0: "Terminal",
}

var Event_Scope_value = map[string]int32{
	"Terminal": 0,
}

func (x Event_Scope) String() string {
	return proto.EnumName(Event_Scope_name, int32(x))
}

func (Event_Scope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0, 0}
}

type Event_Type int32

const (
	Event_KeepAlive       Event_Type = 0
	Event_SessionStarting Event_Type = 1
	Event_SessionStart    Event_Type = 2
	Event_SessionEnd      Event_Type = 3
)

var Event_Type_name = map[int32]string{
	0: "KeepAlive",
	1: "SessionStarting",
	2: "SessionStart",
	3: "SessionEnd",
}

var Event_Type_value = map[string]int32{
	"KeepAlive":       0,
	"SessionStarting": 1,
	"SessionStart":    2,
	"SessionEnd":      3,
}

func (x Event_Type) String() string {
	return proto.EnumName(Event_Type_name, int32(x))
}

func (Event_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0, 1}
}

type Event struct {
	Scope                Event_Scope `protobuf:"varint,1,opt,name=scope,proto3,enum=Event_Scope" json:"scope,omitempty"`
	Type                 Event_Type  `protobuf:"varint,2,opt,name=type,proto3,enum=Event_Type" json:"type,omitempty"`
	Terminal             string      `protobuf:"bytes,3,opt,name=terminal,proto3" json:"terminal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetScope() Event_Scope {
	if m != nil {
		return m.Scope
	}
	return Event_Terminal
}

func (m *Event) GetType() Event_Type {
	if m != nil {
		return m.Type
	}
	return Event_KeepAlive
}

func (m *Event) GetTerminal() string {
	if m != nil {
		return m.Terminal
	}
	return ""
}

func init() {
	proto.RegisterEnum("Event_Scope", Event_Scope_name, Event_Scope_value)
	proto.RegisterEnum("Event_Type", Event_Type_name, Event_Type_value)
	proto.RegisterType((*Event)(nil), "Event")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4a, 0xc5, 0x30,
	0x10, 0x45, 0x5f, 0xde, 0x6b, 0xb4, 0x9d, 0xd6, 0x1a, 0x46, 0x84, 0xe2, 0xc6, 0x92, 0x55, 0x57,
	0x5d, 0xe8, 0x17, 0x28, 0x74, 0xa5, 0xab, 0xb6, 0x2b, 0x77, 0x55, 0x07, 0x09, 0xd4, 0x24, 0x34,
	0xa1, 0xd0, 0x8f, 0xf4, 0x9f, 0x24, 0xb1, 0xc8, 0x5b, 0xde, 0x73, 0x2f, 0x87, 0x19, 0xc8, 0x69,
	0x25, 0xed, 0x5b, 0xbb, 0x18, 0x6f, 0xe4, 0x0f, 0x03, 0xde, 0x85, 0x8c, 0x12, 0xb8, 0xfb, 0x30,
	0x96, 0x2a, 0x56, 0xb3, 0xa6, 0x7c, 0x28, 0xda, 0x88, 0xdb, 0x21, 0xb0, 0xfe, 0xaf, 0xc2, 0x7b,
	0x48, 0xfc, 0x66, 0xa9, 0x3a, 0xc6, 0x49, 0xbe, 0x4f, 0xc6, 0xcd, 0x52, 0x1f, 0x0b, 0xbc, 0x83,
	0xd4, 0xd3, 0xf2, 0xad, 0xf4, 0x34, 0x57, 0xa7, 0x9a, 0x35, 0x59, 0xff, 0x9f, 0xe5, 0x2d, 0xf0,
	0x28, 0xc3, 0x02, 0xd2, 0x71, 0x87, 0xe2, 0x20, 0x5f, 0x21, 0x09, 0x02, 0xbc, 0x82, 0xec, 0x85,
	0xc8, 0x3e, 0xcd, 0x6a, 0x25, 0x71, 0xc0, 0x1b, 0xb8, 0x1e, 0xc8, 0x39, 0x65, 0xf4, 0xe0, 0xa7,
	0xc5, 0x2b, 0xfd, 0x25, 0x18, 0x0a, 0x28, 0xce, 0xa1, 0x38, 0x62, 0x09, 0xb0, 0x93, 0x4e, 0x7f,
	0x8a, 0xd3, 0xf3, 0xe5, 0x1b, 0x0f, 0x87, 0xb8, 0xf7, 0x8b, 0xf8, 0xdf, 0xe3, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9e, 0xd0, 0x59, 0xa1, 0xee, 0x00, 0x00, 0x00,
}
